In [ ]:
import pyodbc

In [ ]:
class ConexaoBD():
 def conexao(self):
  return pyodbc.connect (driver = '{SQL Server}', server = 'TI08', database = 'empresa', trusted_connection = 'yes')

In [ ]:
bd = ConexaoBD()
conexao = bd.conexao()

In [ ]:
class Categoria:
 def __init__ (self, conexao):
  self.conexao = conexao
 def criar (self):
  ddl = '''
   create table Categoria (
   id int primary key identity (1, 1),
   nome varchar (32),
   descricao text
  );
  '''
  with self.conexao:
   self.conexao.execute (ddl)
 
 def ler(self):
  cursor = self.conexao.cursor ()
  cursor.execute ('select * from Categoria')
  for linha in cursor:
   print (linha)

In [ ]:
categoria = Categoria (conexao)
categoria.criar()

In [ ]:
categoria = Categoria (conexao)
categoria.ler()

(1, 'celulares', 'telefones celulares')

In [ ]:
class Vendedor:
 def __init__ (self, conexao):
  self.conexao = conexao
 def criar (self):
  ddl = '''
   CREATE TABLE Vendedor (
   cpf varchar (14) primary key,
   nome varchar (128),
   email varchar (128),
   telefone varchar (20),
   endereco varchar (256)
  );
  '''
  with self.conexao:
   self.conexao.execute(ddl)

 def ler(self):
  cursor = self.conexao.cursor ()
  cursor.execute ('select * from Vendedor')
  for linha in cursor:
   print (linha)

In [ ]:
vendedor = Vendedor(conexao)
vendedor.criar()

In [ ]:
vendedor = Vendedor(conexao)
vendedor.ler()

In [ ]:
class Produto:
 def __init__(self, conexao):
  self.conexao = conexao
 def criar(self):
  ddl = '''
   CREATE TABLE Produto (
   id int primary key identity (1, 1),
   nome varchar (128),
   descricao text,
   marca varchar (32),
   id_categoria int foreign key references Categoria (id)
  );
  '''
  with self.conexao:
   self.conexao.execute(ddl)

 def ler(self):
  cursor = self.conexao.cursor ()
  cursor.execute ('select * from Produto')
  for linha in cursor:
   print (linha)

In [ ]:
produto = Produto(conexao)
produto.criar()

In [ ]:
produto = Produto(conexao)
produto.ler()

In [ ]:
class VendedorProduto:
 def __init__(self, conexao):
  self.conexao = conexao
 def criar(self):
  ddl = '''
   CREATE TABLE VendedorProduto (
   id int primary key identity (1, 1),
   cpf_vendedor varchar (14) foreign key references Vendedor (cpf),
   id_produto int foreign key references Produto (id),
   quantidade int,
   preco decimal
  );
  '''
  with self.conexao:
   self.conexao.execute(ddl)

 def ler(self):
  cursor = self.conexao.cursor ()
  cursor.execute ('select * from VendedorProduto')
  for linha in cursor:
   print (linha)

In [ ]:
vendeProdu = VendedorProduto(conexao)
vendeProdu.criar()

In [ ]:
vendeProdu = VendedorProduto(conexao)
vendeProdu.ler()